### PR TITLE
Fix type lint errors

### LINKED ISSUE #148: Cleanup remaining lints
So we can add linting to CI

### PR DESCRIPTION
**Pull request by benalleng**
#148 

Not 100% sure that these type declarations are the correct way to fix these lints as I'm not totally familiar with handling Rust~Typescipt types

### Wontfix 
nostr-tools import SimplePool error

### CODE REVIEW

File: src/components/waitlist/WaitlistAlreadyIn.tsx [hunk 1]
```diff
@@ -9,7 +9,7 @@ const relayUrls = [
     "wss://eden.nostr.land"
 ];
 
-import { SimplePool } from "nostr-tools";
```
Comment (benalleng) [inline src/components/waitlist/WaitlistAlreadyIn.tsx:12]: This the the fix I am wondering the most about as it produces a inline lint in my nvim stating 
```
const pool = new SimplePool(); ~~This expression is not constructable.
```

Comment (futurepaul) [reply src/components/waitlist/WaitlistAlreadyIn.tsx:12]: yeah tbh I've been ignoring nostr-tools stuff because we're going to rip it out when we are done with the waitlist

Comment (benalleng) [reply src/components/waitlist/WaitlistAlreadyIn.tsx:12]: especially as 'nostr-tools' recommends the previous import

[nostr-tools readme file](https://github.com/nbd-wtf/nostr-tools/blob/b9a7f814aaa08a4b1cec705517b664390abd3f69/README.md?plain=1#L136)

wondering how else we can solve this lint

Comment (benalleng) [reply src/components/waitlist/WaitlistAlreadyIn.tsx:12]: going to go ahead and revert this one

File: src/state/megaStore.tsx [hunk 2]
```diff
@@ -248,46 +245,46 @@ export const Provider: ParentComponent = (props) => {
         actions.fetchUserStatus().then((status) => {
             setState({ user_status: status });
 
+            function handleExisting() {
```
Comment (futurepaul) [inline src/state/megaStore.tsx:248]: I don't normally like defining new functions inline but it def cleans this up

**Review by futurepaul — APPROVED** [review]
sweet this is a good improvement. I think eventually we might want to get these typescript definitions to part of the `mutiny-wasm` package so it's easier to stay in sync but haven't looked into how to do that yet
